DROP TABLE IF EXISTS CURRENCY;
DROP TABLE IF EXISTS EXCHANGE_RATE_HISTORY;

CREATE TABLE CURRENCY (
    CODE varChar(3) PRIMARY KEY UNIQUE,
    NAME varChar(255) NOT NULL
);

CREATE TABLE EXCHANGE_RATE_HISTORY (
    ID int AUTO_INCREMENT PRIMARY KEY,
    CURRENCY_CODE varchar(3),
    RATE double NOT NULL,
    DATE DATE NOT NULL,
    FOREIGN KEY (CURRENCY_CODE) REFERENCES CURRENCY(CODE)
)